# TU Muenchen — Shibboleth (TUM-WAYF)
uni: tum
auth_type: Shibboleth
auth_url: https://www.shibboleth.tum.de/idp/shibboleth
licensed_sites:
  - link.springer.com
  - degruyter.com
  - ebookcentral.proquest.com
  - tib.eu
  - jstor.org
  - wiley.com
  - tandfonline.com
  - sciencedirect.com
bib_pickup_url: https://opac.ub.tum.de
